/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { IOperationResult } from '@pa-client/power-code-sdk/lib/';
import type { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import type { ContosoTasks } from '../Models/ContosoTasksModel';

export class ContosoTasksService {
  private static readonly dataSourceName = 'contosotasks';

  public static async create(record: Omit<ContosoTasks, 'ID'>): Promise<IOperationResult<ContosoTasks>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<ContosoTasks, 'ID'>, ContosoTasks>(
      ContosoTasksService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<ContosoTasks, 'ID'>>): Promise<IOperationResult<ContosoTasks>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<ContosoTasks, 'ID'>>, ContosoTasks>(
      ContosoTasksService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(ContosoTasksService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<ContosoTasks>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<ContosoTasks>(
      ContosoTasksService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<ContosoTasks[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<ContosoTasks>(
      ContosoTasksService.dataSourceName,
      options
    );
    return result;
  }
}
