/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { IOperationResult } from '@pa-client/power-code-sdk/lib/';
import type { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import type { ContosoTrending } from '../Models/ContosoTrendingModel';

export class ContosoTrendingService {
  private static readonly dataSourceName = 'contosotrending';

  public static async create(record: Omit<ContosoTrending, 'ID'>): Promise<IOperationResult<ContosoTrending>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<ContosoTrending, 'ID'>, ContosoTrending>(
      ContosoTrendingService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<ContosoTrending, 'ID'>>): Promise<IOperationResult<ContosoTrending>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<ContosoTrending, 'ID'>>, ContosoTrending>(
      ContosoTrendingService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(ContosoTrendingService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<ContosoTrending>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<ContosoTrending>(
      ContosoTrendingService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<ContosoTrending[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<ContosoTrending>(
      ContosoTrendingService.dataSourceName,
      options
    );
    return result;
  }
}
