/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { IOperationResult } from '@pa-client/power-code-sdk/lib/';
import type { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import type { ContosoHero } from '../Models/ContosoHeroModel';

export class ContosoHeroService {
  private static readonly dataSourceName = 'contosohero';

  public static async create(record: Omit<ContosoHero, 'ID'>): Promise<IOperationResult<ContosoHero>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<ContosoHero, 'ID'>, ContosoHero>(
      ContosoHeroService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<ContosoHero, 'ID'>>): Promise<IOperationResult<ContosoHero>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<ContosoHero, 'ID'>>, ContosoHero>(
      ContosoHeroService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(ContosoHeroService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<ContosoHero>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<ContosoHero>(
      ContosoHeroService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<ContosoHero[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<ContosoHero>(
      ContosoHeroService.dataSourceName,
      options
    );
    return result;
  }
}
