/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { IOperationResult } from '@pa-client/power-code-sdk/lib/';
import type { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import type { ContosoQuickLinks } from '../Models/ContosoQuickLinksModel';

export class ContosoQuickLinksService {
  private static readonly dataSourceName = 'contosoquicklinks';

  public static async create(record: Omit<ContosoQuickLinks, 'ID'>): Promise<IOperationResult<ContosoQuickLinks>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<ContosoQuickLinks, 'ID'>, ContosoQuickLinks>(
      ContosoQuickLinksService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<ContosoQuickLinks, 'ID'>>): Promise<IOperationResult<ContosoQuickLinks>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<ContosoQuickLinks, 'ID'>>, ContosoQuickLinks>(
      ContosoQuickLinksService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(ContosoQuickLinksService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<ContosoQuickLinks>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<ContosoQuickLinks>(
      ContosoQuickLinksService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<ContosoQuickLinks[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<ContosoQuickLinks>(
      ContosoQuickLinksService.dataSourceName,
      options
    );
    return result;
  }
}
