/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { IOperationResult } from '@pa-client/power-code-sdk/lib/';
import type { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import type { ContosoNewsHub } from '../Models/ContosoNewsHubModel';

export class ContosoNewsHubService {
  private static readonly dataSourceName = 'contosonewshub';

  public static async create(record: Omit<ContosoNewsHub, 'ID'>): Promise<IOperationResult<ContosoNewsHub>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<ContosoNewsHub, 'ID'>, ContosoNewsHub>(
      ContosoNewsHubService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<ContosoNewsHub, 'ID'>>): Promise<IOperationResult<ContosoNewsHub>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<ContosoNewsHub, 'ID'>>, ContosoNewsHub>(
      ContosoNewsHubService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(ContosoNewsHubService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<ContosoNewsHub>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<ContosoNewsHub>(
      ContosoNewsHubService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<ContosoNewsHub[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<ContosoNewsHub>(
      ContosoNewsHubService.dataSourceName,
      options
    );
    return result;
  }
}
